# Generated by Django 4.2.29 on 2026-04-16 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumerisationOCR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='ocr_images/')),
                ('ocr_text_brut', models.TextField(blank=True, default='')),
                ('donnees_extraites', models.JSONField(blank=True, default=dict)),
                ('score_confiance', models.FloatField(default=0.0)),
                ('statut', models.CharField(choices=[('EnAttente', 'En attente'), ('Valide', 'Validé'), ('Rejete', 'Rejeté')], default='EnAttente', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte_cree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acts.actenaissance')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
