# Generated by Django 4.2.29 on 2026-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_nin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITOYEN', 'Citoyen'), ('OFFICIER_EC', 'Officier EC'), ('ARCHIVISTE', 'Archiviste'), ('ADMIN_BUNEC', 'Admin BUNEC'), ('MAIRE', 'Maire'), ('RESP_SEC', 'Responsable Sécurité'), ('HOPITAL', 'Hôpital')], default='CITOYEN', max_length=32),
        ),
    ]
