# Generated by Django 4.2.29 on 2026-04-16 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mairie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=120)),
                ('departement', models.CharField(blank=True, default='', max_length=120)),
                ('commune', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='mairies_mai_region_014cef_idx'), models.Index(fields=['code'], name='mairies_mai_code_855ef2_idx')],
            },
        ),
    ]
