# Generated by Django 4.2.29 on 2026-04-16 08:08

import acts.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_acte', models.CharField(max_length=30, unique=True)),
                ('nom_enfant', models.CharField(max_length=150)),
                ('prenom_enfant', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('heure_naissance', models.TimeField(blank=True, null=True)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('EnValidation', 'EnValidation'), ('EnCorrection', 'EnCorrection'), ('Annulé', 'Annulé'), ('Rectifié', 'Rectifié')], default='EnValidation', max_length=16)),
                ('delai_declaration', models.IntegerField(default=0)),
                ('jugement_requis', models.BooleanField(default=False)),
                ('ref_jugement', models.CharField(blank=True, max_length=120, null=True)),
                ('signature_rsa', models.TextField(blank=True, null=True)),
                ('qr_code_sha256', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('version', models.IntegerField(default=1)),
                ('source_acte', models.CharField(choices=[('Saisie', 'Saisie'), ('OCR', 'OCR'), ('Scan', 'Scan')], default='Saisie', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère')], max_length=8)),
                ('nom', acts.fields.EncryptedCharField(max_length=150)),
                ('prenom', acts.fields.EncryptedCharField(max_length=150)),
                ('nin', acts.fields.EncryptedCharField(max_length=64)),
                ('statut_mariage', models.CharField(choices=[('MARIE', 'Marié'), ('NON_MARIE', 'Non marié')], default='NON_MARIE', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='acts.actenaissance')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeCitoyenne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_demande', models.CharField(choices=[('COPIE_INTEGRALE', 'Copie intégrale'), ('EXTRAIT_SANS_FILIATION', 'Extrait sans filiation')], max_length=24)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=12)),
                ('mode_livraison', models.CharField(choices=[('TELECHARGEMENT', 'Téléchargement'), ('COURRIER', 'Courrier')], default='TELECHARGEMENT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('traitee_at', models.DateTimeField(blank=True, null=True)),
                ('acte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='acts.actenaissance')),
            ],
        ),
    ]
