# Generated by Django 4.2.29 on 2026-04-16 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acts', '0001_initial'),
        ('users', '0001_initial'),
        ('mairies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecitoyenne',
            name='citoyen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='mairie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mairies.mairie'),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='officier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.officierec'),
        ),
        migrations.AddIndex(
            model_name='actenaissance',
            index=models.Index(fields=['nom_enfant'], name='acts_actena_nom_enf_ff6764_idx'),
        ),
        migrations.AddIndex(
            model_name='actenaissance',
            index=models.Index(fields=['date_naissance'], name='acts_actena_date_na_35558b_idx'),
        ),
        migrations.AddIndex(
            model_name='actenaissance',
            index=models.Index(fields=['mairie'], name='acts_actena_mairie__8dbddd_idx'),
        ),
    ]
